# Generated by Django 4.2.3 on 2023-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.CharField(default="German", max_length=100),
        ),
    ]
