# Generated by Django 4.2.3 on 2023-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                choices=[
                    ("Arabic", "Arabic"),
                    ("Chinese (Simplified)", "Chinese (Simplified)"),
                    ("Chinese (Traditional)", "Chinese (Traditional)"),
                    ("English", "English"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Hindi", "Hindi"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Korean", "Korean"),
                    ("Portuguese", "Portuguese"),
                    ("Russian", "Russian"),
                    ("Spanish", "Spanish"),
                    ("Bengali", "Bengali"),
                    ("Punjabi", "Punjabi"),
                    ("Telugu", "Telugu"),
                    ("Marathi", "Marathi"),
                    ("Tamil", "Tamil"),
                    ("Turkish", "Turkish"),
                    ("Vietnamese", "Vietnamese"),
                ],
                default="German",
                max_length=50,
            ),
        ),
    ]
