# Generated by Django 4.2.3 on 2023-08-02 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_language_language"),
    ]

    operations = [
        migrations.DeleteModel(name="Language",),
    ]
