# Generated by Django 4.2.3 on 2023-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_delete_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="question_text", new_name="question_prompt",
        ),
        migrations.RemoveField(model_name="question", name="language",),
        migrations.AddField(
            model_name="question",
            name="question",
            field=models.CharField(default="History of Czech Republic", max_length=100),
        ),
    ]
