# Generated by Django 4.2.3 on 2023-08-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_question_text_question_question_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option4",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(
                default="History of Czech Republic", max_length=100, null=True
            ),
        ),
    ]
