# Generated by Django 4.2.3 on 2023-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_question_option1_alter_question_option2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
