# Generated by Django 4.2.3 on 2023-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_quizresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
