# Generated by Django 4.2.3 on 2023-08-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_question_question"),
    ]

    operations = [
        migrations.RemoveField(model_name="quizresult", name="timestamp",),
    ]
